# Generated by Django 5.2.6 on 2025-09-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premon', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
