# Generated by Django 5.2.6 on 2025-09-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='premon',
            new_name='prenom',
        ),
    ]
