# Generated by Django 5.2.6 on 2025-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_rename_premon_etudiant_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
